### ISSUE TITLE
The build is not a required check — real breaks land on main and block `shipyard pr` repo-wide

### ISSUE THREAD

**Issue by danielraffel** [danielraffel/pulp#6087]
## What happened

The only **required** status check on `main` is **`Enforce version & skill sync`**. The **build is not required**. So code that does not compile can — and does — land on `main`, and it then blocks *every other PR*, because Shipyard's pre-push **diff-cover gate runs a full build**.

Two real instances in the last day:

### 1. `core/view` — macOS non-Skia build broken on `main` (fixed in #6079)
`core/view/platform/mac/plugin_view_host_mac.mm` had:
```cpp
#ifdef PULP_HAS_SKIA
#include <pulp/view/frame_clock.hpp>
#include <pulp/view/host_frame_pump.hpp>   // ← behind the Skia guard
...
#endif
```
…but the **shared Core Graphics path** uses them outside any Skia guard: the CG host owns a `HostFramePump frame_pump_` member and calls `should_dispatch_host_frame` / `begin_host_frame` / `advance_host_frame`.

Any build **without `PULP_HAS_SKIA`** therefore failed with 8 errors (`unknown type name 'HostFramePump'`, `no member named 'should_dispatch_host_frame' in namespace 'pulp::view'`, plus cascading `PluginViewHost` conversion errors). Introduced by the frame-delta work (#6072).

**Impact:** `shipyard pr` failed its pre-push build for *any* PR in the repo — that is how it was found (while opening an unrelated skill PR). Verified fix: `cmake --build … --target pulp-view-core` went 8 errors → `[100%] Built target`.

### 2. `test_wam_adapter.cpp` — same class, earlier
#5958 migrated `WamProcessorBridge::process` to the planar signature but did not update `test/test_wam_adapter.cpp`, which still passed interleaved `float*`. It did not compile. It landed anyway (the build isn't required), broke `main`, and blocked Shipyard validation until fixed. Its red `macos` leg was dismissed as flake precisely *because* it wasn't a required check and reds there are routinely noise.

## Why this keeps happening

- **Required-check set is too thin.** A non-required red is indistinguishable from the known-flaky self-hosted `macos` noise, so genuine build failures get waved through.
- **The failure is invisible until it blocks someone else.** Nothing on `main` alerts; the next person to run `shipyard pr` eats it.
- **Non-Skia / CG configurations are under-covered** — #6079 only reproduces without `PULP_HAS_SKIA`, which is exactly the config Shipyard's diff-cover build uses.

## Suggested fixes

1. **Make at least one build a required check.** It does not have to be the slow self-hosted `macos` leg — a fast compile-only job (e.g. the same non-Skia/CG configuration Shipyard's diff-cover uses) would have caught **both** of these.
2. **Cover the non-Skia configuration in CI explicitly** — both bugs above only manifest there.
3. **Alert on a red build on `main`** (not just on PRs), so a break is caught at land time rather than by the next person who runs `shipyard pr`.
4. If the self-hosted `macos` flakiness is what's blocking making a build required, fix/quarantine the flaky tests first — the current state means *no* build signal is trusted, which is how real breaks slip through.

Companion issue: #6086 (a stale-base PR silently reverted another PR's files; no gate caught that either — same underlying theme of a too-thin required-check set).
Related: #5958, #6072, #6079.
